### PR TITLE
Adjust spacing on desktop and mobile footer

### PR DESCRIPTION
**Pull request by mandily-p**
I adjusted the spacing and changed the background colour to grey to de-emphasize it on the page.

I can't/don't want to figure out how to make that text wrap beside the CC image, but Brett or Brad is welcome to hop into my PR to add it :)

**Current version**
screen shot 2018-11-20 at 11 25 55 pm
screen shot 2018-11-20 at 11 27 16 pm

**Updated version**
screen shot 2018-11-20 at 11 26 07 pm
screen shot 2018-11-20 at 11 26 37 pm

### CODE REVIEW

**Comment by mandily-p** [comment]
Related to #556 and #542

**Comment by kathreenriel** [comment]
@mandily-p we've come full circle - the background colour on  footer was originally grey.

**Comment by mandily-p** [comment]
hahaha. Why did you change it to blue @kathreenriel ?

**Comment by kathreenriel** [comment]
#267 completed change the colour of the footer to blue last October 2017. I don't remember the reasoning - admittedly I really like the symmetry of blue on the top and bottom of the screen

**Pull request merged**
