### PR TITLE
Reorganize table layout

### PR DESCRIPTION
**Pull request by mandily-p**
I'm not sure why there's so many deletions and additions that are the same in the code. When I tried to just commit the actual part that I changed, things got messed up. So I reverted and am submitting as is. Let me know if that's not going to fly and I need to rebase. 

Resolves git issue #534 User friendly layout of Edit events page.

screen shot 2018-09-25 at 9 03 55 pm

### CODE REVIEW

**Comment by bdolor** [comment]
thanks for the PR Amanda! I'll take a closer look at it soon. Is there an existing issue this is intended to resolve?

**Comment by mandily-p** [comment]
Yes, #534. I updated the main message with the link.

**Comment by bdolor** [comment]
thanks!

**Comment by brettjforsyth** [comment]
Not sure who needs to fix the build check issues

**Comment by bdolor** [comment]
they're being re-run

**Comment by bdolor** [comment]
@brettjforsyth - `phpcs` is throwing errors. `composer standards` will tell you which ones. 

image

**Comment by brettjforsyth** [comment]
Yup just not my pull request so not sure who should be fixing them.

**Comment by bdolor** [comment]
@mandily-p - please resolve the errors above

**Comment by brettjforsyth** [comment]
@mandily-p Do you want me to fix this?

**Pull request merged**
