### PR TITLE
Custom donut colors

### PR DESCRIPTION
**Pull request by brettjforsyth**
Modified the donut to pull colours from the event categories. You can change the colors by editing the color picker of the event category. Solves #379

### CODE REVIEW

**Comment by brettjforsyth** [comment]
So I created a branch from a relatively old version of the code to see if I could get the color picker to work and it still fails. Check out https://github.com/brettjforsyth/eypd/tree/old-dev to see where I created the branch from. Are you able to confirm that older version of the code have a working color picker?

**Comment by brettjforsyth** [comment]
@bdolor what version of the code is https://eypd.bccampus.ca running? as they are working there. I just want to branch that to see if I can get pickers working locally with that version.

**Comment by bdolor** [comment]
@brettjforsyth - parent theme default setting needs to be slider 'do not display'. Go into the dashboard, Appearance ->CBox Theme Options -> look for homepage setting, turn it off: 

image

These kinds of gotcha default settings can be overwritten at the theme level using the `.ini` files in `/engine/config/options.ini`

**Comment by bdolor** [comment]
taking this out of the defer list works: https://github.com/BCcampus/eypd/blob/dev/functions.php#L38

**Comment by brettjforsyth** [comment]
Ah fun

**Comment by kathreenriel** [comment]
Hmmm...I don't think this is working 
custom colours

**Pull request merged**
