### PR TITLE
anchor tags

### PR DESCRIPTION
**Pull request by bdolor**
chips away at https://github.com/BCcampus/eypd/issues/407
- anchor tags
- headers
- header padding

### CODE REVIEW

**Comment by alex-418** [comment]
mama mia that's a lot of white space

**Comment by mandily-p** [comment]
@alex-418 This is late - I know, but can we add in smooth scrolling to these jump links so it's not so jarring for the user?

**Comment by mandily-p** [comment]
I'm testing this on an account with only one past event. 

The `completed` link is scrolling the page past the `My past events`, when it should be scrolling to about 50 pixels before the `My past events` heading.

The `needed` link is scrolling the page to `My past events`, when it should be scrolling to the `Event summary`

**Comment by bdolor** [comment]
smooth-scrolling feature request should be captured in another ticket.

The landing of the anchor tags at specific places on the page is dependent on #414

**Pull request merged**
